### ISSUE TITLE
Koristiti switch kada je potrebno

### ISSUE THREAD

**Issue by TakoAgencyDev** [ifiala/zadaci-bamboo#1]

**Comment by vedraninho** [comment]
Krivim računom sam kreirao issue, evo sad sa pravim:

https://github.com/ifiala/zadaci-bamboo/blob/e650be7bb793485bb67381c376653887d42007ea/vodic.py#L72-L82
nije u biti problem ali u slučaju da svi ishodi ovise o vrijednosti istog parametra koristi switch čitljivije je i more clean:
```
switch (answer5)
  case 1: userProfile['Business'] = 100;
          break;
  case 2: userProfile['Family'] = 100;
          break;
  case 3: userProfile['Adventure'] = 100;
          break;
  case 4: userProfile['Casual'] = 100;
          break;
```

**Comment by ifiala** [comment]
Inače bih to koristio, ali kako python nema switch case, radio sam preko if-else, ali ako je potrebno mogu napisat funkciju koja bi se ponašala kao switch-case

**Comment by vedraninho** [comment]
~Zatvaram~ možeš zatvoriti, googleao sam prije nego sam to napisao ali sad vidim da sam našao implementaciju switcha.
