### ISSUE TITLE
Računanje udjela mase 

### ISSUE THREAD

**Issue by vedraninho** [ifiala/zadaci-bamboo#2]
https://github.com/ifiala/zadaci-bamboo/blob/e650be7bb793485bb67381c376653887d42007ea/rostilj.py#L27

Ovdje dijeliš ukupnu masu sa 3 bez obzira koliko je vrsta mesa odabrano. Pregledaj, ja bih rekao da trebaš 340 podijeliti sa brojem odabranih vrsta.

**Comment by ifiala** [comment]
Mislio sam da se samo jedna vrsta mesa može izbacit, evo popravljeno
