### ISSUE TITLE
Provjera paketa

### ISSUE THREAD

**Issue by vedraninho** [ifiala/zadaci-bamboo#3]
https://github.com/ifiala/zadaci-bamboo/blob/e650be7bb793485bb67381c376653887d42007ea/rostilj.py#L236

Rekao bih da ako je `paketBoolean1 == True` da se "kod koji odlucuje koliko paketa2 treba" neće okinuti. Nije zabranjena kombinacija paketa.

+ Bilo bi bolje da vidiš koji paket osigurava veću uštedu, skineš tih paketa koliko možeš, pa onda skineš mogući broj sljedećih... pa na kraju poskidaš ostatak istom logikom.

**Comment by ifiala** [comment]
Ovo je samo provjera od kojeg paketa krenuti, ali napravio sam i provjeru može li se ostatak koji preostaje kupiti putem paketa dva sa uštedom:

https://github.com/ifiala/zadaci-bamboo/blob/e650be7bb793485bb67381c376653887d42007ea/rostilj.py#L146-L164

**Comment by vedraninho** [comment]
Promaklo mi je, izgleda dobro.
