### ISSUE TITLE
Ponavljanje istog koda

### ISSUE THREAD

**Issue by vedraninho** [ifiala/zadaci-bamboo#4]
https://github.com/ifiala/zadaci-bamboo/blob/e650be7bb793485bb67381c376653887d42007ea/rostilj.py#L171-L220

Ovaj dio koda ti se ponavlja 3 puta, samim time kod je manje čitljiv i manje održiv. Mislim da kada riješiš [ovaj issue](https://github.com/ifiala/zadaci-bamboo/issues/3#issue-724384563) da ti se neće ponavljati ali ako bude, umotaj ga u neku funkciju.

**Comment by ifiala** [comment]
Rješeno
